app:
  app-name: "vendeur Backend"
  version: "1.0.0"

server:
  port: 8081  # Port where your Spring Boot application will run

spring:
  application:
    name: vendeur
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/vendeur  # Keycloak issuer URI
          jwk-set-uri: http://localhost:8080/realms/vendeur/protocol/openid-connect/certs  # Keycloak JWK set URI
