app:
  app-name: "vendeur Backend"
  version: "1.0.0"

server:
  port: 8081

spring:
  application:
    name: vendeur
  data:
    mongodb:
      uri: mongodb://localhost:27017/vendeur_dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/vendeur
          jwk-set-uri: http://localhost:8080/realms/vendeur/protocol/openid-connect/certs

openId :
  client_id: vendeur-dev-api


keycloak:
  server: http://localhost:8080
  realms: vendeur
  tokenUrl: http://localhost:8080/realms/vendeur/protocol/openid-connect/token
  clientId: vendeur-dev-api
  cdentls:
    aU1: vendeuradmin
    aP1: internal
  api:
    admin:
      createUser: ${keycloak.server}/admin/realms/${keycloak.realms}/users

